// MIT License

// Copyright (c) 2025 Meng Chengzhen, in Shandong University

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include "simgen.h"
#include "stringop.hpp"

#include <cerrno>
#include <chrono>
#include <cstdlib>
#include <deque>
#include <iomanip>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace simgen {

const string CodeTab = "    ";

inline static std::string cppStringLiteral(const std::string &s) {
    std::string out = "\"";
    for (char ch : s) {
        switch (ch) {
            case '\\': out += "\\\\"; break;
            case '"': out += "\\\""; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default: out.push_back(ch); break;
        }
    }
    out += "\"";
    return out;
}

const string TickFunctionName = "on_current_tick";
const string ApplyTickFunctionName = "apply_next_tick";

const string RegisterClassName = "VulRegister";
const string RegisterArrayClassName = "VulRegisterArray";
const string BlockRAMClassName = "VulBRAM";
const string BlockRAM1RWClassName = "VulBRAM1RW";
const string ROMClassName = "VulROM";
const string QueueClassName = "VulQueue";

string genCurrentTimeString() {
    std::chrono::system_clock::time_point now = std::chrono::system_clock::now();
    std::time_t tt = std::chrono::system_clock::to_time_t(now);
    std::tm* ptm = std::localtime(&tt);
    std::ostringstream oss;
    oss << std::put_time(ptm, "%Y-%m-%d %H:%M:%S");
    return oss.str();
}

vector<string> genHeaderPrelude() {
    static const vector<string> code_header_prelude = {
        "// This header file is generated by VulSim SimGen tool.\n",
        "// Do not modify this file directly.\n",
    };
    vector<string> out = code_header_prelude;
    out.push_back("// Generated on: " + genCurrentTimeString() + "\n");
    out.push_back("\n");
    out.push_back("#pragma once\n");
    out.push_back("\n");
    return out;
}

namespace {

struct ParsedInstanceExpr {
    string base_name;
    vector<string> index_exprs;
};

enum class IndexExprKind {
    Constant,
    Variable,
    Wildcard,
};

struct ParsedIndexExpr {
    IndexExprKind kind = IndexExprKind::Constant;
    char var_symbol = 0;
    int64_t offset = 0;
    string const_expr;
};

static bool isIdentStart(char c) {
    return std::isalpha(static_cast<unsigned char>(c)) || c == '_';
}

static bool isIdentChar(char c) {
    return std::isalnum(static_cast<unsigned char>(c)) || c == '_';
}

static ParsedInstanceExpr parseInstanceExpr(const string &expr_raw) {
    const string expr = stringop::trim(expr_raw);
    if (expr.empty()) {
        return {};
    }
    size_t pos = 0;
    if (!isIdentStart(expr[pos])) {
        throw VulException("Invalid instance expression: '" + expr + "'");
    }
    while (pos < expr.size() && isIdentChar(expr[pos])) {
        ++pos;
    }
    ParsedInstanceExpr out;
    out.base_name = expr.substr(0, pos);
    while (pos < expr.size()) {
        while (pos < expr.size() && std::isspace(static_cast<unsigned char>(expr[pos]))) {
            ++pos;
        }
        if (pos >= expr.size()) break;
        if (expr[pos] != '[') {
            throw VulException("Invalid instance expression: '" + expr + "'");
        }
        const size_t begin = ++pos;
        int depth = 1;
        for (; pos < expr.size(); ++pos) {
            if (expr[pos] == '[') ++depth;
            else if (expr[pos] == ']') {
                --depth;
                if (depth == 0) break;
            }
        }
        if (pos >= expr.size() || expr[pos] != ']') {
            throw VulException("Unmatched '[' in instance expression: '" + expr + "'");
        }
        out.index_exprs.push_back(stringop::trim(expr.substr(begin, pos - begin)));
        ++pos;
    }
    return out;
}

static bool tryParseSimpleInt(const string &expr, int64_t &value) {
    const string trimmed = stringop::trim(expr);
    if (trimmed.empty()) return false;
    char *end = nullptr;
    errno = 0;
    long long parsed = std::strtoll(trimmed.c_str(), &end, 0);
    if (errno != 0 || end == nullptr || *end != '\0') {
        return false;
    }
    value = static_cast<int64_t>(parsed);
    return true;
}

static ParsedIndexExpr parseIndexExprTemplate(const string &expr_raw) {
    const string expr = stringop::trim(expr_raw);
    if (expr == "*") {
        ParsedIndexExpr out;
        out.kind = IndexExprKind::Wildcard;
        return out;
    }
    int64_t const_value = 0;
    if (tryParseSimpleInt(expr, const_value)) {
        ParsedIndexExpr out;
        out.kind = IndexExprKind::Constant;
        out.offset = const_value;
        out.const_expr = expr;
        return out;
    }

    auto parse_var_plus_const = [&](char symbol) -> std::optional<ParsedIndexExpr> {
        const size_t symbol_pos = expr.find(symbol);
        if (symbol_pos == string::npos) return std::nullopt;
        string lhs = stringop::trim(expr.substr(0, symbol_pos));
        string rhs = stringop::trim(expr.substr(symbol_pos + 1));
        int64_t offset = 0;
        if (lhs.empty() && rhs.empty()) {
            ParsedIndexExpr out;
            out.kind = IndexExprKind::Variable;
            out.var_symbol = symbol;
            out.offset = 0;
            return out;
        }
        if (lhs.empty()) {
            if (rhs.empty()) return std::nullopt;
            if (rhs[0] == '+') {
                if (!tryParseSimpleInt(rhs.substr(1), offset)) return std::nullopt;
            } else if (rhs[0] == '-') {
                if (!tryParseSimpleInt(rhs.substr(1), offset)) return std::nullopt;
                offset = -offset;
            } else {
                return std::nullopt;
            }
            ParsedIndexExpr out;
            out.kind = IndexExprKind::Variable;
            out.var_symbol = symbol;
            out.offset = offset;
            return out;
        }
        if (rhs.empty()) {
            if (lhs.back() != '+' && lhs.back() != '-') return std::nullopt;
            const char op = lhs.back();
            if (!tryParseSimpleInt(lhs.substr(0, lhs.size() - 1), offset)) return std::nullopt;
            if (op == '-') offset = -offset;
            ParsedIndexExpr out;
            out.kind = IndexExprKind::Variable;
            out.var_symbol = symbol;
            out.offset = offset;
            return out;
        }
        return std::nullopt;
    };

    if (auto parsed = parse_var_plus_const('$')) return *parsed;
    if (auto parsed = parse_var_plus_const('?')) return *parsed;

    ParsedIndexExpr out;
    out.kind = IndexExprKind::Constant;
    out.const_expr = expr;
    return out;
}

vector<ConfigRealValue> parseConcreteInstanceIndices(
    const string &decl_name,
    const vector<ConfigRealValue> &dims,
    const string &concrete_name
) {
    vector<ConfigRealValue> out;
    if (concrete_name == decl_name) {
        return out;
    }
    if (!concrete_name.starts_with(decl_name + "__")) {
        throw VulException("Instance '" + concrete_name + "' does not match declaration '" + decl_name + "'");
    }
    size_t pos = decl_name.size() + 2;
    while (pos <= concrete_name.size()) {
        size_t next = concrete_name.find("__", pos);
        string token = concrete_name.substr(pos, next == string::npos ? string::npos : next - pos);
        if (token.empty()) {
            throw VulException("Invalid array instance name: '" + concrete_name + "'");
        }
        out.push_back(static_cast<ConfigRealValue>(std::stoll(token)));
        if (next == string::npos) {
            break;
        }
        pos = next + 2;
    }
    if (out.size() != dims.size()) {
        throw VulException("Array instance name '" + concrete_name + "' has wrong number of indices");
    }
    return out;
}

string childPtrFieldName(const string &inst_name, const vector<ConfigRealValue> &indices) {
    string out = "__instptr_" + inst_name;
    for (ConfigRealValue idx : indices) {
        out += "[" + std::to_string(idx) + "]";
    }
    return out;
}

string childPtrFieldName(const VulStaticModuleInstance &parent, const string &concrete_name) {
    for (const auto &[inst_name, inst] : parent.instances) {
        if (!inst.isArrayed()) {
            if (concrete_name == inst_name) {
                return childPtrFieldName(inst_name, {});
            }
            continue;
        }
        if (concrete_name == inst_name || concrete_name.starts_with(inst_name + "__")) {
            return childPtrFieldName(inst_name, parseConcreteInstanceIndices(inst_name, inst.array_dims, concrete_name));
        }
    }
    throw VulException("Child pointer target not found for instance '" + concrete_name + "'");
}

std::array<int32_t, 2> sourceLoopVarDims(const vector<VulConnIndexExpr> &req_indices) {
    std::array<int32_t, 2> dims = { -1, -1 };
    for (size_t dim = 0; dim < req_indices.size(); ++dim) {
        if (req_indices[dim].kind != VulConnIndexKind::LoopVar || req_indices[dim].offset != 0) continue;
        dims[req_indices[dim].loop_dim] = static_cast<int32_t>(dim);
    }
    return dims;
}

string replaceLoopVarsWithInstIdx(const string &expr, const std::array<int32_t, 2> &loop_dims) {
    string out;
    out.reserve(expr.size() * 2);
    for (char c : expr) {
        if (c == '$') {
            if (loop_dims[0] < 0) throw VulException("Source loop variable '$' is not defined");
            out += "__instidx" + std::to_string(loop_dims[0]);
        } else if (c == '?') {
            if (loop_dims[1] < 0) throw VulException("Source loop variable '?' is not defined");
            out += "__instidx" + std::to_string(loop_dims[1]);
        } else {
            out.push_back(c);
        }
    }
    return out;
}

string childPtrFieldExpr(const VulStaticModuleInstance &parent, const string &base_name, const vector<VulConnIndexExpr> &req_indices, const vector<VulConnIndexExpr> &indices) {
    auto inst_it = parent.instances.find(base_name);
    if (inst_it == parent.instances.end()) {
        throw VulException("Instance '" + base_name + "' not found");
    }
    const auto loop_dims = sourceLoopVarDims(req_indices);
    string out = "__instptr_" + base_name;
    for (size_t dim = 0; dim < indices.size(); ++dim) {
        const auto &parsed = indices[dim];
        if (parsed.kind == VulConnIndexKind::LoopVar) {
            if (loop_dims[parsed.loop_dim] < 0) {
                throw VulException("Loop variable used before being defined on the source side");
            }
            string expr_str = "__instidx" + std::to_string(loop_dims[parsed.loop_dim]);
            if (parsed.offset > 0) expr_str = "(" + expr_str + " + " + std::to_string(parsed.offset) + "u)";
            if (parsed.offset < 0) expr_str = "(" + expr_str + " - " + std::to_string(-parsed.offset) + "u)";
            out += "[" + expr_str + "]";
        } else if (parsed.kind == VulConnIndexKind::GeneralExpr) {
            out += "[" + replaceLoopVarsWithInstIdx(parsed.expr, loop_dims) + "]";
        } else if (parsed.kind == VulConnIndexKind::Wildcard) {
            out += "[__instidx" + std::to_string(dim) + "]";
        } else {
            out += "[" + parsed.expr + "]";
        }
    }
    return out;
}

string localServiceIndexExpr(
    const vector<VulConnIndexExpr> &req_indices,
    const vector<ConfigRealValue> &inst_dims,
    size_t dim
) {
    (void)inst_dims;
    const auto loop_dims = sourceLoopVarDims(req_indices);
    const auto &parsed = req_indices[dim];
    if (parsed.kind == VulConnIndexKind::Wildcard) {
        return "__instidx" + std::to_string(dim);
    }
    if (parsed.kind == VulConnIndexKind::LoopVar) {
        if (loop_dims[parsed.loop_dim] < 0) {
            throw VulException("Loop variable used before being defined on the source side");
        }
        if (parsed.offset == 0) return "__instidx" + std::to_string(loop_dims[parsed.loop_dim]);
        string expr = "__instidx" + std::to_string(loop_dims[parsed.loop_dim]);
        if (parsed.offset > 0) expr = "(" + expr + " + " + std::to_string(parsed.offset) + "u)";
        if (parsed.offset < 0) expr = "(" + expr + " - " + std::to_string(-parsed.offset) + "u)";
        return expr;
    }
    if (parsed.kind == VulConnIndexKind::GeneralExpr) {
        return replaceLoopVarsWithInstIdx(parsed.expr, loop_dims);
    }
    return parsed.expr;
}

vector<string> buildArrayWrapperTemplateLines(
    const VulStaticModuleInstance &mod,
    const string &inst_name,
    const VulStaticInstanceDecl &inst,
    const string &req_name,
    const VulStaticReqServ &req,
    const string &argname,
    const string &call_prefix,
    const string &rettype
) {
    vector<string> lines;
    bool emitted = false;
    for (const auto &raw_conn : mod.req_connections) {
        if (raw_conn.req_instance.empty()) continue;
        if (raw_conn.req_instance_base != inst_name || raw_conn.req_name != req_name) continue;
        if (raw_conn.req_indices.size() != inst.array_dims.size()) continue;
        for (const auto &idx : raw_conn.serv_indices) {
            if (idx.kind == VulConnIndexKind::GeneralExpr) {
                return {};
            }
        }

        vector<string> cond_terms;
        for (size_t dim = 0; dim < raw_conn.req_indices.size(); ++dim) {
            const auto &parsed = raw_conn.req_indices[dim];
            if (parsed.kind == VulConnIndexKind::ConstantExpr) {
                cond_terms.push_back("__instidx" + std::to_string(dim) + " == " + parsed.expr);
            }
        }

        string guard = cond_terms.empty() ? "true" : cond_terms[0];
        for (size_t i = 1; i < cond_terms.size(); ++i) {
            guard += " && " + cond_terms[i];
        }

        if (!raw_conn.serv_instance.empty()) {
            auto target_it = mod.instances.find(raw_conn.serv_instance_base);
            if (target_it == mod.instances.end()) {
                continue;
            }
            const auto &target_inst = target_it->second;
            vector<string> bounds;
            const auto loop_dims = sourceLoopVarDims(raw_conn.req_indices);
            for (size_t dim = 0; dim < raw_conn.serv_indices.size(); ++dim) {
                const auto &parsed = raw_conn.serv_indices[dim];
                if (parsed.kind != VulConnIndexKind::LoopVar) continue;
                if (loop_dims[parsed.loop_dim] < 0) {
                    return {};
                }
                string src_expr = "__instidx" + std::to_string(loop_dims[parsed.loop_dim]);
                const auto target_dim = target_inst.array_dims[dim];
                if (parsed.offset > 0) {
                    const auto offset = static_cast<uint64_t>(parsed.offset);
                    if (offset > static_cast<uint64_t>(target_dim)) {
                        guard = "false";
                        break;
                    }
                    bounds.push_back("(" + src_expr + " < " + std::to_string(static_cast<uint64_t>(target_dim) - offset) + "u)");
                } else if (parsed.offset < 0) {
                    const auto offset = static_cast<uint64_t>(-parsed.offset);
                    if (offset > static_cast<uint64_t>(target_dim)) {
                        guard = "false";
                        break;
                    }
                    bounds.push_back("(" + src_expr + " >= " + std::to_string(offset) + "u)");
                } else {
                    bounds.push_back("(" + src_expr + " < " + std::to_string(target_dim) + "u)");
                }
            }
            for (const auto &b : bounds) {
                guard += (guard.empty() ? "" : " && ") + b;
            }

            lines.push_back(CodeTab + string(emitted ? "else if (" : "if (") + guard + ") {\n");
            string child_access = childPtrFieldExpr(mod, raw_conn.serv_instance_base, raw_conn.req_indices, raw_conn.serv_indices);
            if (req.is_arrayed) {
                lines.push_back(CodeTab + CodeTab + call_prefix + child_access + "->" + raw_conn.serv_name + "<IDX>(" + argname + ");\n");
            } else {
                lines.push_back(CodeTab + CodeTab + call_prefix + child_access + "->" + raw_conn.serv_name + "(" + argname + ");\n");
            }
            if (rettype == "void") lines.push_back(CodeTab + CodeTab + "return;\n");
            lines.push_back(CodeTab + "}\n");
            emitted = true;
            continue;
        }

        if (raw_conn.serv_name.empty()) continue;
        lines.push_back(CodeTab + string(emitted ? "else if (" : "if (") + guard + ") {\n");
        bool generated_dispatch = false;
        size_t wildcard_dim = 0;
        for (size_t dim = 0; dim < raw_conn.req_indices.size(); ++dim) {
            if (raw_conn.req_indices[dim].kind == VulConnIndexKind::Wildcard) {
                wildcard_dim = dim;
                auto serv_it = mod.services.find(raw_conn.serv_name);
                if (serv_it != mod.services.end() && serv_it->second.is_arrayed) {
                    for (uint32_t idx = 0; idx < serv_it->second.array_size; ++idx) {
                        string branch = (idx == 0 ? "if" : "else if");
                        lines.push_back(CodeTab + CodeTab + branch + " (" + localServiceIndexExpr(raw_conn.req_indices, inst.array_dims, wildcard_dim) + " == " + std::to_string(idx) + ") {\n");
                        lines.push_back(CodeTab + CodeTab + CodeTab + call_prefix + raw_conn.serv_name + "<" + std::to_string(idx) + ">(" + argname + ");\n");
                        if (rettype == "void") lines.push_back(CodeTab + CodeTab + CodeTab + "return;\n");
                        lines.push_back(CodeTab + CodeTab + "}\n");
                    }
                    generated_dispatch = true;
                }
                break;
            }
        }
        if (!generated_dispatch) {
            string call_line;
            if (req.is_arrayed) {
                call_line = raw_conn.serv_name + "<IDX>(" + argname + ");";
            } else {
                call_line = raw_conn.serv_name + "(" + argname + ");";
            }
            lines.push_back(CodeTab + CodeTab + call_prefix + call_line + "\n");
            if (rettype == "void") lines.push_back(CodeTab + CodeTab + "return;\n");
        }
        lines.push_back(CodeTab + "}\n");
        emitted = true;
    }
    return lines;
}

string replaceLoopVarsForEval(const string &expr, const vector<ConfigRealValue> &loop_vars) {
    string out;
    out.reserve(expr.size() * 2);
    for (char c : expr) {
        if (c == '$') {
            out += "__v0";
        } else if (c == '?') {
            out += "__v1";
        } else {
            out.push_back(c);
        }
    }
    (void)loop_vars;
    return out;
}

ConfigRealValue evalConnExprWithLoopVars(
    const string &expr,
    const VulStaticConfigLib &config_lib,
    const vector<ConfigRealValue> &loop_vars
) {
    VulStaticConfigLib eval_cfg = config_lib;
    if (loop_vars.size() > 0) eval_cfg["__v0"] = loop_vars[0];
    if (loop_vars.size() > 1) eval_cfg["__v1"] = loop_vars[1];
    return calculateConstexprValue(replaceLoopVarsForEval(expr, loop_vars), eval_cfg);
}

VulStaticConfigLib mergedModuleConfigLib(const VulStaticModuleInstance &mod) {
    VulStaticConfigLib cfg = mod.local_parameters;
    for (const auto &entry : mod.local_consts) {
        cfg[entry.first] = entry.second;
    }
    return cfg;
}

template<typename Fn>
void forEachIndexTuple(const vector<ConfigRealValue> &dims, Fn fn);
vector<ConfigRealValue> childArrayDims(const VulStaticModuleInstance &mod);
bool childIsArrayTemplate(const VulStaticModuleInstance &mod);

vector<string> buildExplicitArrayWrapperLines(
    const VulStaticModuleInstance &mod,
    const string &inst_name,
    const VulStaticInstanceDecl &inst,
    const string &req_name,
    const VulStaticReqServ &req,
    const string &argname,
    const string &call_prefix,
    const string &rettype
) {
    vector<string> lines;
    bool emitted = false;
    const auto cfg = mergedModuleConfigLib(mod);
    forEachIndexTuple(inst.array_dims, [&](const vector<ConfigRealValue> &indices) {
        for (const auto &raw_conn : mod.req_connections) {
            if (raw_conn.req_instance.empty()) continue;
            if (raw_conn.req_instance_base != inst_name || raw_conn.req_name != req_name) continue;
            if (raw_conn.req_indices.size() != inst.array_dims.size()) continue;

            vector<ConfigRealValue> loop_vars(2, 0);
            vector<bool> loop_set(2, false);
            bool matched = true;
            for (size_t dim = 0; dim < raw_conn.req_indices.size(); ++dim) {
                const auto &idx = raw_conn.req_indices[dim];
                if (idx.kind == VulConnIndexKind::ConstantExpr) {
                    if (calculateConstexprValue(idx.expr, cfg) != indices[dim]) {
                        matched = false;
                        break;
                    }
                } else if (idx.kind == VulConnIndexKind::LoopVar) {
                    if (idx.offset != 0) {
                        matched = false;
                        break;
                    }
                    if (loop_set[idx.loop_dim] && loop_vars[idx.loop_dim] != indices[dim]) {
                        matched = false;
                        break;
                    }
                    loop_vars[idx.loop_dim] = indices[dim];
                    loop_set[idx.loop_dim] = true;
                } else {
                    matched = false;
                    break;
                }
            }
            if (!matched) continue;

            string cond = "if (";
            for (size_t dim = 0; dim < indices.size(); ++dim) {
                if (dim > 0) cond += " && ";
                cond += "__instidx" + std::to_string(dim) + " == " + std::to_string(indices[dim]);
            }
            cond += ") {\n";
            lines.push_back(CodeTab + string(emitted ? "else " : "") + cond);

            if (!raw_conn.serv_instance.empty()) {
                auto target_it = mod.instances.find(raw_conn.serv_instance_base);
                if (target_it == mod.instances.end()) {
                    throw VulException("Instance '" + raw_conn.serv_instance_base + "' not found");
                }
                vector<ConfigRealValue> target_indices;
                bool valid_target = true;
                for (size_t dim = 0; dim < raw_conn.serv_indices.size(); ++dim) {
                    const auto &idx = raw_conn.serv_indices[dim];
                    ConfigRealValue target_idx = 0;
                    if (idx.kind == VulConnIndexKind::ConstantExpr || idx.kind == VulConnIndexKind::GeneralExpr) {
                        target_idx = evalConnExprWithLoopVars(idx.expr, cfg, loop_vars);
                    } else if (idx.kind == VulConnIndexKind::LoopVar) {
                        target_idx = loop_vars[idx.loop_dim] + idx.offset;
                    } else {
                        valid_target = false;
                        break;
                    }
                    if (target_idx < 0 || target_idx >= target_it->second.array_dims[dim]) {
                        valid_target = false;
                        break;
                    }
                    target_indices.push_back(target_idx);
                }
                if (!valid_target) {
                    lines.pop_back();
                    continue;
                }
                string child_access = childPtrFieldName(raw_conn.serv_instance_base, target_indices);
                if (req.is_arrayed) {
                    lines.push_back(CodeTab + CodeTab + call_prefix + child_access + "->" + raw_conn.serv_name + "<IDX>(" + argname + ");\n");
                } else {
                    lines.push_back(CodeTab + CodeTab + call_prefix + child_access + "->" + raw_conn.serv_name + "(" + argname + ");\n");
                }
            } else {
                bool generated_dispatch = false;
                for (size_t dim = 0; dim < raw_conn.req_indices.size(); ++dim) {
                    if (raw_conn.req_indices[dim].kind != VulConnIndexKind::Wildcard) continue;
                    auto serv_it = mod.services.find(raw_conn.serv_name);
                    if (serv_it != mod.services.end() && serv_it->second.is_arrayed) {
                        ConfigRealValue wildcard_idx = indices[dim];
                        lines.push_back(CodeTab + CodeTab + call_prefix + raw_conn.serv_name + "<" + std::to_string(wildcard_idx) + ">(" + argname + ");\n");
                        generated_dispatch = true;
                    }
                    break;
                }
                if (!generated_dispatch) {
                    if (req.is_arrayed) {
                        lines.push_back(CodeTab + CodeTab + call_prefix + raw_conn.serv_name + "<IDX>(" + argname + ");\n");
                    } else {
                        lines.push_back(CodeTab + CodeTab + call_prefix + raw_conn.serv_name + "(" + argname + ");\n");
                    }
                }
            }
            if (rettype == "void") lines.push_back(CodeTab + CodeTab + "return;\n");
            lines.push_back(CodeTab + "}\n");
            emitted = true;
            return;
        }
    });
    return lines;
}

vector<ConfigRealValue> childArrayDims(const VulStaticModuleInstance &mod) {
    if (!mod.parent) {
        return {};
    }
    auto it = mod.parent->instances.find(mod.instance_path.back());
    if (it == mod.parent->instances.end()) {
        return {};
    }
    return it->second.array_dims;
}

bool childIsArrayTemplate(const VulStaticModuleInstance &mod) {
    return !childArrayDims(mod).empty();
}

template<typename Fn>
void forEachIndexTuple(const vector<ConfigRealValue> &dims, Fn fn) {
    vector<ConfigRealValue> indices(dims.size(), 0);
    std::function<void(size_t)> dfs = [&](size_t dim) {
        if (dim == dims.size()) {
            fn(indices);
            return;
        }
        for (ConfigRealValue idx = 0; idx < dims[dim]; ++idx) {
            indices[dim] = idx;
            dfs(dim + 1);
        }
    };
    if (dims.empty()) {
        fn(indices);
    } else {
        dfs(0);
    }
}

string moduleWrapperBaseName(const VulStaticModuleInstance &mod) {
    if (childIsArrayTemplate(mod)) {
        return mod.instance_path.back();
    }
    return mod.instance_path.back();
}

string nestedArrayType(const string &leaf_type, const vector<ConfigRealValue> &dims) {
    string out = leaf_type;
    for (auto it = dims.rbegin(); it != dims.rend(); ++it) {
        out = "std::array<" + out + ", " + std::to_string(*it) + ">";
    }
    return out;
}

vector<shared_ptr<VulStaticModuleInstance>> collectChildrenByDecl(
    const VulStaticModuleInstance &mod,
    const string &inst_name
) {
    vector<shared_ptr<VulStaticModuleInstance>> out;
    for (const auto &child : mod.children) {
        if (child->instance_path.back() == inst_name) {
            out.push_back(child);
        }
    }
    return out;
}

const VulStaticModuleInstance &findChildTemplateByName(
    const VulStaticModuleInstance &mod,
    const string &name
) {
    for (const auto &child : mod.children) {
        if (child->instance_path.back() == name) {
            return *child;
        }
    }
    for (const auto &[inst_name, inst] : mod.instances) {
        if (inst.isArrayed() && (name == inst_name || name.starts_with(inst_name + "__"))) {
            for (const auto &child : mod.children) {
                if (child->instance_path.back() == inst_name) {
                    return *child;
                }
            }
        }
    }
    throw VulException("Child instance template not found: " + name);
}

} // namespace

vector<string> genStaticConfigHeaderCode(const VulStaticConfigLib &configlib) {
    vector<string> out_lines = genHeaderPrelude();

    out_lines.push_back("#include \"common.h\"\n");
    out_lines.push_back("#include \"fixint.hpp\"\n");
    out_lines.push_back("\n");
    out_lines.push_back("// Configuration Items\n");
    out_lines.push_back("\n");

    for (const auto &cfg : configlib) {
        out_lines.push_back("constexpr int64_t " + cfg.first + " = " + std::to_string(cfg.second) + ";\n");
    }

    return out_lines;
}

string _genStaticMemberTypeStr(const VulStaticBundleMember &member) {
    string type_str;
    string base_type = member.type.toString();
    if (!member.dims.empty()) {
        for (const auto &dim : member.dims) {
            type_str += "std::array<";
        }
        type_str += base_type;
        for (uint32_t i = member.dims.size(); i > 0; i--) {
            type_str += ", " + std::to_string(member.dims[i-1]) + ">";
        }
    } else {
        type_str = base_type;
    }
    return type_str;
}

vector<string> _genStaticBundle(const VulStaticBundle &bundle) {
    vector<string> out_lines;

    if (bundle.is_alias) {
        if (!bundle.members.empty()) {
            string alias_target = _genStaticMemberTypeStr(bundle.members[0]);
            out_lines.push_back("using " +  bundle.name + " = " + alias_target + ";\n");
        }
    } else if (!bundle.enum_members.empty()) {
        out_lines.push_back("enum class " + bundle.name + " {\n");
        for (const auto &enum_member : bundle.enum_members) {
            if (enum_member.has_value) {
                out_lines.push_back(CodeTab + enum_member.name + " = " + std::to_string(enum_member.value) + ",\n");
            } else {
                out_lines.push_back(CodeTab + enum_member.name + ",\n");
            }
        }
        out_lines.push_back("};\n");
    } else {
        out_lines.push_back("struct " + bundle.name + " {\n");
        for (const auto &member : bundle.members) {
            string type_str = _genStaticMemberTypeStr(member);
            out_lines.push_back(CodeTab + type_str + " " + member.name + ";\n");
        }
        out_lines.push_back("};\n");
    }

    return out_lines;
}

vector<string> genStaticBundle(const VulStaticBundle &bundle) {
    return _genStaticBundle(bundle);
}

vector<string> genStaticBundleHeaderCode(const VulStaticBundleLib &bundlelib) {
    vector<string> out_lines = genHeaderPrelude();

    out_lines.push_back("#include \"common.h\"\n");
    out_lines.push_back("#include \"config.h\"\n");
    out_lines.push_back("#include \"fixint.hpp\"\n");
    out_lines.push_back("\n");
    out_lines.push_back("// Bundle Definitions\n");
    out_lines.push_back("\n");


    for (const auto &bundle : bundlelib) {
        auto bundle_lines = _genStaticBundle(bundle);
        out_lines.insert(out_lines.end(), bundle_lines.begin(), bundle_lines.end());
        out_lines.push_back("\n");
    }

    return out_lines;
}

StaticModuleCodeHpp genStaticModuleCodeHpp(const VulStaticModuleInstance &mod, const vector<VulTracedSignal> &traced_signals) {

    vector<string> decl_include_field;
    vector<string> decl_public_field;
    vector<string> decl_private_field;

    vector<string> impl_field;
    vector<string> impl_init_field;
    vector<string> impl_commit_field;
    vector<string> impl_sys_reset_field;
    vector<string> impl_reg_reset_field;

    string mod_class_name = mod.simClassName();

    // local params and consts
    for (const auto &param : mod.local_parameters) {
        decl_private_field.push_back("static constexpr int64_t " + param.first + " = " + std::to_string(param.second) + ";\n");
    }
    for (const auto &constvar : mod.local_consts) {
        decl_private_field.push_back("static constexpr int64_t " + constvar.first + " = " + std::to_string(constvar.second) + ";\n");
    }
    // local bundles
    for (const auto &bundle_entry : mod.local_bundles) {
        auto bundle_lines = _genStaticBundle(bundle_entry);
        decl_private_field.insert(decl_private_field.end(), bundle_lines.begin(), bundle_lines.end());
        decl_private_field.push_back("\n");
    }

    // generate request declarations
    for (const auto &req_entry : mod.requests) {
        const auto &req = req_entry.second;
        string rettype = req.returnType();
        string argnames = req.signatureArgNameList();
        string arglists = req.signatureArgOnly();
        const bool is_arrayed = req.is_arrayed;

        if (is_arrayed) {
            decl_private_field.push_back("template <uint32_t IDX = 0>\n");
            decl_private_field.push_back(rettype + " " + req_entry.first + "(" + arglists + ");\n");
        } else {
            decl_private_field.push_back(rettype + " " + req_entry.first + "(" + arglists + ");\n");
        }
        decl_private_field.push_back("\n");

        string call_prefix = (rettype == "void" ? "" : "return ");
        string wrapper_name = "__parent->__wrapper_" + moduleWrapperBaseName(mod) + "_" + req_entry.first;
        string wrapper_prefix_args;
        const auto mod_array_dims = childArrayDims(mod);
        if (!mod_array_dims.empty()) {
            for (size_t i = 0; i < mod_array_dims.size(); ++i) {
                if (!wrapper_prefix_args.empty()) wrapper_prefix_args += ", ";
                wrapper_prefix_args += "__array_idx_" + std::to_string(i);
            }
            if (!argnames.empty()) {
                wrapper_prefix_args += ", ";
            }
        }
        wrapper_prefix_args += argnames;
        if (is_arrayed) {
            impl_field.push_back("template <uint32_t IDX>\n");
            impl_field.push_back(rettype + " " + mod_class_name + "::" + req_entry.first + "(" + arglists + ") {\n");
            impl_field.push_back(CodeTab + call_prefix + wrapper_name + "<IDX>(" + wrapper_prefix_args + ");\n");
        } else {
            impl_field.push_back(rettype + " " + mod_class_name + "::" + req_entry.first + "(" + arglists + ") {\n");
            impl_field.push_back(CodeTab + call_prefix + wrapper_name + "(" + wrapper_prefix_args + ");\n");
        }
        impl_field.push_back("}\n");
        impl_field.push_back("\n");
    }

    // generate service declarations
    for (const auto &serv_entry : mod.services) {
        const auto &serv = serv_entry.second;
        string rettype = serv.returnType();
        string argnames = serv.signatureArgNameList();
        string arglists = serv.signatureArgOnly();
        const bool is_arrayed = serv.is_arrayed;

        if (is_arrayed) {
            decl_public_field.push_back("template <uint32_t IDX = 0>\n");
            decl_public_field.push_back(rettype + " " + serv_entry.first + "(" + arglists + ");\n");
        } else {
            decl_public_field.push_back(rettype + " " + serv_entry.first + "(" + arglists + ");\n");
        }

        // implemented by logic block, or connented to child module's service
        auto lb_iter = mod.serv_logic_blocks.find(serv_entry.first);
        if (lb_iter != mod.serv_logic_blocks.end()) {
            if (rettype == "void") {
                if (is_arrayed) {
                    impl_field.push_back("template <uint32_t IDX>\n");
                }
                impl_field.push_back("void " + mod_class_name + "::" + serv_entry.first + "(" + arglists + ") {\n");
                impl_field.insert(impl_field.end(), lb_iter->second.codelines.begin(), lb_iter->second.codelines.end());
                impl_field.push_back("}\n");
            } else {
                if (is_arrayed) {
                    decl_private_field.push_back("template <uint32_t IDX = 0>\n");
                    decl_private_field.push_back("bool __cond_" + serv_entry.first + "(" + arglists + ");\n");
                    decl_private_field.push_back("template <uint32_t IDX = 0>\n");
                    decl_private_field.push_back("void __impl_" + serv_entry.first + "(" + arglists + ");\n");
                } else {
                    decl_private_field.push_back("bool __cond_" + serv_entry.first + "(" + arglists + ");\n");
                    decl_private_field.push_back("void __impl_" + serv_entry.first + "(" + arglists + ");\n");
                }

                if (is_arrayed) {
                    impl_field.push_back("template <uint32_t IDX>\n");
                }
                impl_field.push_back("bool " + mod_class_name + "::" + serv_entry.first + "(" + arglists + ") {\n");
                if (is_arrayed) {
                    impl_field.push_back(CodeTab + "bool cond = __cond_" + serv_entry.first + "<IDX>(" + argnames + ");\n");
                    impl_field.push_back(CodeTab + "if (cond) __impl_" + serv_entry.first + "<IDX>(" + argnames + ");\n");
                } else {
                    impl_field.push_back(CodeTab + "bool cond = __cond_" + serv_entry.first + "(" + argnames + ");\n");
                    impl_field.push_back(CodeTab + "if (cond) __impl_" + serv_entry.first + "(" + argnames + ");\n");
                }
                impl_field.push_back(CodeTab + "return cond;\n");
                impl_field.push_back("}\n");

                if (is_arrayed) {
                    impl_field.push_back("template <uint32_t IDX>\n");
                }
                impl_field.push_back("bool " + mod_class_name + "::__cond_" + serv_entry.first + "(" + arglists + ") {\n");
                impl_field.insert(impl_field.end(), lb_iter->second.cond_codelines.begin(), lb_iter->second.cond_codelines.end());
                impl_field.push_back("}\n");

                if (is_arrayed) {
                    impl_field.push_back("template <uint32_t IDX>\n");
                }
                impl_field.push_back("void " + mod_class_name + "::__impl_" + serv_entry.first + "(" + arglists + ") {\n");
                impl_field.insert(impl_field.end(), lb_iter->second.codelines.begin(), lb_iter->second.codelines.end());
                impl_field.push_back("}\n");
            }
        }

        decl_public_field.push_back("\n");
        impl_field.push_back("\n");
    }

    // generate query declarations
    for (const auto &query_entry : mod.queries) {
        const string &query_name = query_entry.first;
        const auto &query = query_entry.second;
        auto lb_iter = mod.query_logic_blocks.find(query_name);
        if (lb_iter == mod.query_logic_blocks.end()) {
            throw VulException("Missing logic block for query " + query_name);
        }

        decl_public_field.push_back(query.ret_type.toString() + " " + query_name + "() const;\n");
        impl_field.push_back(query.ret_type.toString() + " " + mod_class_name + "::" + query_name + "() const {\n");
        impl_field.insert(impl_field.end(), lb_iter->second.codelines.begin(), lb_iter->second.codelines.end());
        impl_field.push_back("}\n");
        impl_field.push_back("\n");
    }

    // generate register
    for (const auto &reg : mod.registers) {
        const auto &sig = reg.signature;
        string type_str;
        string base_type = sig.type;
        if (sig.uint_length > 0) {
            base_type = std::string(UIntClassName) + "<" + std::to_string(sig.uint_length) + ">";
        }
        if (!reg.dims.empty()) {
            type_str += RegisterArrayClassName + "<" + base_type;
            for (const auto &dim : reg.dims) {
                type_str += "," + std::to_string(dim);
            }
            if (reg.ports > 1) {
                type_str = type_str + ", " + std::to_string(reg.ports);
            }
            type_str += ">";

            decl_private_field.push_back(type_str + " " + reg.name + ";\n");
            // decl_private_field.push_back("template <uint32_t P = 0>\n");
            // decl_private_field.push_back("void " + reg.name + "_setnext(const uint64_t idx, const " + base_type + " &value) {\n");
            // decl_private_field.push_back(CodeTab + reg.name + ".setnext<P>(idx, value);\n");
            // decl_private_field.push_back("}\n");
            decl_private_field.push_back("\n");
        } else {
            if (reg.ports > 1) {
                type_str = RegisterClassName + "<" + base_type + ", " + std::to_string(reg.ports) + ">";
            } else {
                type_str = RegisterClassName + "<" + base_type + ">";
            }

            decl_private_field.push_back(type_str + " " + reg.name + ";\n");
            // decl_private_field.push_back("template <uint32_t P = 0>\n");
            // decl_private_field.push_back("void " + reg.name + "_setnext(const " + base_type + " &value) {\n");
            // decl_private_field.push_back(CodeTab + reg.name + ".setnext<P>(value);\n");
            // decl_private_field.push_back("}\n");
            // decl_private_field.push_back("const " + base_type + " &" + reg.name + "_get() const {\n");
            // decl_private_field.push_back(CodeTab + "return " + reg.name + ".get();\n");
            // decl_private_field.push_back("}\n");
            decl_private_field.push_back("\n");
        }
        VulStaticBundleMember sig_as_member;
        sig_as_member.name = reg.name;
        sig_as_member.type = reg.signature;
        sig_as_member.dims = reg.dims;
        impl_reg_reset_field.push_back("{\n");
        impl_reg_reset_field.push_back(_genStaticMemberTypeStr(sig_as_member) + " " + reg.name + ";\n");
        impl_reg_reset_field.insert(impl_reg_reset_field.end(), reg.reset_codelines.begin(), reg.reset_codelines.end());
        impl_reg_reset_field.push_back("this->" + reg.name + ".reset(" + reg.name + ");\n");
        impl_reg_reset_field.push_back("}\n");

        impl_commit_field.push_back(reg.name + "." + ApplyTickFunctionName + "();\n");
    }

    // generate wire
    for (const auto &wire : mod.wires) {
        const auto &sig = wire.signature;
        string type_str = sig.toString();

        decl_private_field.push_back(type_str + " " + wire.name + ";\n");
        decl_private_field.push_back("\n");

        impl_commit_field.push_back("{\n");
        impl_commit_field.insert(impl_commit_field.end(), wire.reset_codelines.begin(), wire.reset_codelines.end());
        impl_commit_field.push_back("}\n");
        impl_reg_reset_field.push_back("{\n");
        impl_reg_reset_field.insert(impl_reg_reset_field.end(), wire.reset_codelines.begin(), wire.reset_codelines.end());
        impl_reg_reset_field.push_back("}\n");
    }

    vector<string> bram_resources_files;
    // generate bram
    for (const auto &bram : mod.brams) {
        VulErrorContextGuard context_guard("processing bram " + bram.name);
        string bram_class = "";
        if (bram.read_ports == 0 || bram.write_ports == 0) {
            bram_class = BlockRAM1RWClassName + "<" +
                bram.data_type.toString() + ", " +
                std::to_string(bram.addr_size) + ">";
        } else {
            bram_class = BlockRAMClassName + "<" +
            bram.data_type.toString() + ", " +
            std::to_string(bram.addr_size) + ", " + 
            std::to_string(bram.read_ports) + ", " +
            std::to_string(bram.write_ports) + ">";
        }

        decl_private_field.push_back(bram_class + " " + bram.name + ";\n");
        impl_commit_field.push_back(CodeTab + bram.name + "." + ApplyTickFunctionName + "();\n");
    }
    // generate rom
    for (const auto &rom : mod.roms) {
        VulErrorContextGuard context_guard("processing rom " + rom.name);
        string rom_class = ROMClassName + "<" +
            std::to_string(rom.data_width) + ", " +
            std::to_string(rom.addr_size) + ", " + 
            std::to_string(rom.read_ports) + ">";

        decl_private_field.push_back(rom_class + " " + rom.name + "{\"" + rom.init_path + "\"};\n");
        impl_commit_field.push_back(CodeTab + rom.name + "." + ApplyTickFunctionName + "();\n");
    }

    // generate queues
    for (const auto &queue : mod.queues) {
        VulErrorContextGuard context_guard("processing queue " + queue.name);
        if (queue.depth == 0) {
            throw VulException("Queue must have positive depth");
        }
        if (queue.deq_width == 0 || queue.enq_width == 0) {
            throw VulException("Queue must have positive enq_width and deq_width");
        }
        string queue_param = queue.type.toString() + ", " + std::to_string(queue.depth);
        if (queue.deq_width > 1 || queue.enq_width > 1) {
            queue_param += ", " + std::to_string(queue.enq_width) + ", " + std::to_string(queue.deq_width);
        }
        string queue_class = QueueClassName + "<" + queue_param + ">";
        decl_private_field.push_back(queue_class + " " + queue.name + ";\n");
        impl_commit_field.push_back(CodeTab + queue.name + "." + ApplyTickFunctionName + "();\n");
    }

    // generate instances
    for (const auto &inst_entry : mod.instances) {
        const auto &inst = inst_entry.second;
        const auto &inst_name = inst_entry.first;

        VulErrorContextGuard context_guard("processing child instance " + inst_name);

        auto inst_children = collectChildrenByDecl(mod, inst_name);
        if (inst_children.empty()) {
            throw VulException("Child instance not found");
        }
        shared_ptr<VulStaticModuleInstance> inst_mod_ptr = inst_children.front();

        decl_include_field.push_back("#include \"" + inst_mod_ptr->simDeclPath() + "\"\n");

        string child_class_name = inst_mod_ptr->simClassName();
        string child_instance_ptr_name = "__instptr_" + inst_name;
        if (inst.isArrayed()) {
            decl_private_field.push_back(nestedArrayType("std::unique_ptr<" + child_class_name + ">", inst.array_dims) + " " + child_instance_ptr_name + ";\n");
            forEachIndexTuple(inst.array_dims, [&](const vector<ConfigRealValue> &indices) {
                string init_call = childPtrFieldName(inst_name, indices) + " = std::make_unique<" + child_class_name + ">(this";
                for (ConfigRealValue idx : indices) {
                    init_call += ", " + std::to_string(idx);
                }
                init_call += ");\n";
                impl_init_field.push_back(init_call);
                impl_commit_field.push_back(childPtrFieldName(inst_name, indices) + "->" + ApplyTickFunctionName + "();\n");
                impl_sys_reset_field.push_back(childPtrFieldName(inst_name, indices) + "->reset();\n");
            });
        } else {
            decl_private_field.push_back("std::unique_ptr<" + child_class_name + "> " + child_instance_ptr_name + ";\n");
            impl_init_field.push_back(child_instance_ptr_name + " = std::make_unique<" + child_class_name + ">(this);\n");
            impl_commit_field.push_back(child_instance_ptr_name + "->" + ApplyTickFunctionName + "();\n");
            impl_sys_reset_field.push_back(child_instance_ptr_name + "->reset();\n");
        }

        // connected requests
        for (const auto &req_entry : inst_mod_ptr->requests) {
            const auto &req_name = req_entry.first;
            const auto &req = req_entry.second;
            string rettype = req.returnType();
            string arglists = req.signatureArgOnly();
            string argname = req.signatureArgNameList();
            const bool is_arrayed = req.is_arrayed;
            if (inst.isArrayed()) {
                decl_public_field.push_back(rettype + " __wrapper_" + inst_name + "_" + req_name + "(");
                bool need_comma = false;
                for (size_t dim = 0; dim < inst.array_dims.size(); ++dim) {
                    if (need_comma) decl_public_field.back() += ", ";
                    decl_public_field.back() += "uint32_t __instidx" + std::to_string(dim);
                    need_comma = true;
                }
                if (!arglists.empty()) {
                    if (need_comma) decl_public_field.back() += ", ";
                    decl_public_field.back() += arglists;
                }
                decl_public_field.back() += ") {\n";
            } else if (is_arrayed) {
                decl_public_field.push_back("template <uint32_t IDX = 0>\n");
                decl_public_field.push_back(rettype + " __wrapper_" + inst_name + "_" + req_name + "(" + arglists + ") {\n");
            }
            if (!inst.isArrayed() && !is_arrayed) {
                decl_public_field.push_back(rettype + " __wrapper_" + inst_name + "_" + req_name + "(" + arglists + ") {\n");
            }
            string call_prefix = (rettype == "void" ? "" : "return ");
            if (inst.isArrayed()) {
                auto template_lines = buildArrayWrapperTemplateLines(mod, inst_name, inst, req_name, req, argname, call_prefix, rettype);
                if (!template_lines.empty()) {
                    decl_public_field.insert(decl_public_field.end(), template_lines.begin(), template_lines.end());
                    decl_public_field.push_back(CodeTab + "throw std::out_of_range(\"array child instance index out of range\");\n");
                } else {
                    auto explicit_lines = buildExplicitArrayWrapperLines(mod, inst_name, inst, req_name, req, argname, call_prefix, rettype);
                    decl_public_field.insert(decl_public_field.end(), explicit_lines.begin(), explicit_lines.end());
                    decl_public_field.push_back(CodeTab + "throw std::out_of_range(\"array child instance index out of range\");\n");
                }
            } else {
                // find the connected service
                VulReqServConnection conn;
                bool found_conn = false;
                for (const auto &c : mod.req_connections) {
                    if (c.req_instance == inst_name && c.req_name == req_name) {
                        conn = c;
                        found_conn = true;
                        break;
                    }
                }
                if (!found_conn) {
                    throw VulException("No connection found for request " + req_name + " of instance " + inst_name);
                }
                if (conn.serv_instance.empty()) {
                    // passed to local request/service, directly call the function
                    if (is_arrayed) {
                        decl_public_field.push_back(CodeTab + call_prefix + conn.serv_name + "<IDX>(" + argname + ");\n");
                    } else {
                        decl_public_field.push_back(CodeTab + call_prefix + conn.serv_name + "(" + argname + ");\n");
                    }
                } else {
                    // passed to child module's service
                    if (is_arrayed) {
                        decl_public_field.push_back(CodeTab + call_prefix + childPtrFieldName(mod, conn.serv_instance) + "->" + conn.serv_name + "<IDX>(" + argname + ");\n");
                    } else {
                        decl_public_field.push_back(CodeTab + call_prefix + childPtrFieldName(mod, conn.serv_instance) + "->" + conn.serv_name + "(" + argname + ");\n");
                    }
                }
            }

            decl_public_field.push_back("}\n");
        }
    }

    // exported child services / implicit requests
    std::map<string, vector<VulStaticChildServiceUse>> child_service_groups;
    for (const auto &use : mod.child_service_uses) {
        child_service_groups[use.alias_name].push_back(use);
    }
    for (const auto &group_entry : child_service_groups) {
        const string &alias_name = group_entry.first;
        const auto &group = group_entry.second;
        const auto &target_child = findChildTemplateByName(mod, group.front().instance_name);
        auto serv_iter = target_child.services.find(group.front().service_name);
        if (serv_iter == target_child.services.end()) {
            throw VulException("Service " + group.front().service_name + " not found in child " + target_child.module_name);
        }
        const auto &serv = serv_iter->second;
        string rettype = serv.returnType();
        string arglists = serv.signatureArgOnly();
        string argname = serv.signatureArgNameList();
        const bool is_alias_arrayed = group.front().alias_indexed;
        if (is_alias_arrayed) {
            decl_private_field.push_back("template <uint32_t IDX = 0>\n");
        }
        decl_private_field.push_back(rettype + " " + alias_name + "(" + arglists + ") {\n");
        string call_prefix = (rettype == "void" ? "" : "return ");
        if (!is_alias_arrayed) {
            decl_private_field.push_back(CodeTab + call_prefix + childPtrFieldName(mod, group.front().instance_name) + "->" + group.front().service_name + "(" + argname + ");\n");
        } else {
            decl_private_field.push_back(CodeTab + "static_assert(IDX < " + std::to_string(group.size()) + ", \"Implicit request index out of range\");\n");
            for (size_t i = 0; i < group.size(); ++i) {
                const auto &use = group[i];
                string branch = (i == 0 ? "if constexpr" : "else if constexpr");
                decl_private_field.push_back(CodeTab + branch + " (IDX == " + std::to_string(use.alias_index) + ") {\n");
                decl_private_field.push_back(CodeTab + CodeTab + call_prefix + childPtrFieldName(mod, use.instance_name) + "->" + use.service_name + "(" + argname + ");\n");
                decl_private_field.push_back(CodeTab + "}\n");
            }
        }
        decl_private_field.push_back("}\n");
    }

    std::map<string, vector<VulStaticChildQueryUse>> child_query_groups;
    for (const auto &use : mod.child_query_uses) {
        child_query_groups[use.alias_name].push_back(use);
    }
    for (const auto &group_entry : child_query_groups) {
        const string &alias_name = group_entry.first;
        const auto &group = group_entry.second;
        const auto &target_child = findChildTemplateByName(mod, group.front().instance_name);
        auto query_iter = target_child.queries.find(group.front().query_name);
        if (query_iter == target_child.queries.end()) {
            throw VulException("Query " + group.front().query_name + " not found in child " + target_child.module_name);
        }
        if (!(group.front().ret_type == query_iter->second.ret_type)) {
            throw VulException("USE_CHILD_QUERY return type mismatch for alias " + alias_name);
        }
        const string rettype = query_iter->second.ret_type.toString();
        const bool is_alias_arrayed = group.front().alias_indexed;
        if (is_alias_arrayed) {
            decl_private_field.push_back("template <uint32_t IDX = 0>\n");
        }
        decl_private_field.push_back(rettype + " " + alias_name + "() const {\n");
        if (!is_alias_arrayed) {
            decl_private_field.push_back(CodeTab + "return " + childPtrFieldName(mod, group.front().instance_name) + "->" + group.front().query_name + "();\n");
        } else {
            decl_private_field.push_back(CodeTab + "static_assert(IDX < " + std::to_string(group.size()) + ", \"Child query index out of range\");\n");
            for (size_t i = 0; i < group.size(); ++i) {
                const auto &use = group[i];
                string branch = (i == 0 ? "if constexpr" : "else if constexpr");
                decl_private_field.push_back(CodeTab + branch + " (IDX == " + std::to_string(use.alias_index) + ") {\n");
                decl_private_field.push_back(CodeTab + CodeTab + "return " + childPtrFieldName(mod, use.instance_name) + "->" + use.query_name + "();\n");
                decl_private_field.push_back(CodeTab + "}\n");
            }
        }
        decl_private_field.push_back("}\n");
    }

    // tick functions
    for (uint64_t i = 0; i < mod.tick_blocks.size(); i++) {
        const auto &tick = mod.tick_blocks[i];
        string tick_func_name = "__tick" + std::to_string(i);

        decl_private_field.push_back("void " + tick_func_name + "();\n");

        impl_field.push_back("void " + mod_class_name + "::" + tick_func_name + "() {\n");
        impl_field.insert(impl_field.end(), tick.codelines.begin(), tick.codelines.end());
        impl_field.push_back("}\n");
        impl_field.push_back("\n");
    }

    // helper field
    decl_private_field.insert(decl_private_field.end(), mod.helper_codes.begin(), mod.helper_codes.end());

    // trace
    if (!traced_signals.empty()) {
        for (uint64_t i = 0; i < traced_signals.size(); ++i) {
            const auto &sig = traced_signals[i];
            const bool needs_trace_bitmap = childIsArrayTemplate(mod) && !sig.trace_all_instances;
            string traceid_var = "_trace_id_" + std::to_string(i);
            string tracebitmap_var = "_trace_bitmap_" + std::to_string(i);
            string signal_name = mod.concatInstancePath(".") + "." + sig.signal_path;
            string access_path = "";
            string regname = sig.signal_path;
            const string &signal_path = sig.signal_path;
            const size_t first_dot_pos = signal_path.find('.');
            const size_t first_bracket_pos = signal_path.find('[');
            size_t regname_end_pos = signal_path.size();
            if (first_bracket_pos != string::npos && (first_dot_pos == string::npos || first_bracket_pos < first_dot_pos)) {
                regname_end_pos = first_bracket_pos;
            } else if (first_dot_pos != string::npos) {
                regname_end_pos = first_dot_pos;
            }
            regname = signal_path.substr(0, regname_end_pos);
            access_path = signal_path.substr(regname_end_pos);
            bool is_reg_array = false;
            for (const auto &reg : mod.registers) {
                if (reg.name == regname) {
                    is_reg_array = !reg.dims.empty();
                    break;
                }
            }
            if (!is_reg_array) {
                regname = regname + ".get()"; // .和[]运算符不能被隐式类型转换
            }
            access_path = regname + access_path;
            if (sig.bit_width > 64) {
                access_path = access_path + ".get_data()";
            } else {
                access_path = "static_cast<uint64_t>(" + access_path + ")";
            }

            decl_private_field.push_back("uint32_t " + traceid_var + " = 0;\n");
            if (needs_trace_bitmap) {
                decl_private_field.push_back("bool " + tracebitmap_var + " = false;\n");
            }

            if (childIsArrayTemplate(mod)) {
                impl_init_field.push_back("{\n");
                if (!needs_trace_bitmap) {
                    impl_init_field.push_back(CodeTab + "std::string __trace_signal_name = \"" + mod.concatInstancePath(".") + "\";\n");
                    for (size_t dim = 0; dim < childArrayDims(mod).size(); ++dim) {
                        impl_init_field.push_back(CodeTab + "__trace_signal_name += \"[\" + std::to_string(__array_idx_" + std::to_string(dim) + ") + \"]\";\n");
                    }
                    impl_init_field.push_back(CodeTab + "__trace_signal_name += \"." + sig.signal_path + "\";\n");
                    impl_init_field.push_back(CodeTab + traceid_var + " = trace_registe_signal(__trace_signal_name, " + std::to_string(sig.bit_width) + ");\n");
                } else {
                    impl_init_field.push_back(CodeTab + tracebitmap_var + " = false;\n");
                    for (const auto &filter : sig.instance_index_filters) {
                        string cond;
                        for (size_t dim = 0; dim < filter.size(); ++dim) {
                            if (!filter[dim].has_value()) continue;
                            if (!cond.empty()) cond += " && ";
                            cond += "__array_idx_" + std::to_string(dim) + " == " + std::to_string(*filter[dim]);
                        }
                        if (cond.empty()) {
                            impl_init_field.push_back(CodeTab + tracebitmap_var + " = true;\n");
                            break;
                        }
                        impl_init_field.push_back(CodeTab + "if (" + cond + ") " + tracebitmap_var + " = true;\n");
                    }
                    impl_init_field.push_back(CodeTab + "std::string __trace_signal_name = \"" + mod.concatInstancePath(".") + "\";\n");
                    for (size_t dim = 0; dim < childArrayDims(mod).size(); ++dim) {
                        impl_init_field.push_back(CodeTab + "__trace_signal_name += \"[\" + std::to_string(__array_idx_" + std::to_string(dim) + ") + \"]\";\n");
                    }
                    impl_init_field.push_back(CodeTab + "__trace_signal_name += \"." + sig.signal_path + "\";\n");
                    impl_init_field.push_back(CodeTab + "if (" + tracebitmap_var + ") " + traceid_var + " = trace_registe_signal(__trace_signal_name, " + std::to_string(sig.bit_width) + ");\n");
                }
                impl_init_field.push_back("}\n");
            } else {
                impl_init_field.push_back(traceid_var + " = trace_registe_signal(\"" + signal_name + "\", " + std::to_string(sig.bit_width) + ");\n");
            }
            if (needs_trace_bitmap) {
                impl_commit_field.push_back("if (" + tracebitmap_var + ") trace_record(" + traceid_var + ", " + access_path + ");\n");
            } else {
                impl_commit_field.push_back("trace_record(" + traceid_var + ", " + access_path + ");\n");
            }
        }
    }

    // preparation done, start generating code lines

    vector<string> decl = genHeaderPrelude();
    decl.push_back("#include \"common.h\"\n");
    decl.push_back("#include \"config.h\"\n");
    decl.push_back("#include \"bundle.h\"\n");
    decl.push_back("#include \"vullib.h\"\n");
    decl.push_back("#include <stdexcept>\n");
    decl.push_back("\n");

    // include child module decls
    for (const auto &line : decl_include_field) {
        decl.push_back(line);
    }
    decl.push_back("\n");

    // declare parent class
    string parent_class_name = mod.parent->simClassName();
    decl.push_back("class " + parent_class_name + ";\n");
    decl.push_back("\n");

    // start class declaration
    decl.push_back("class " + mod_class_name + " {\n");

    decl.push_back("private:\n");
    decl.push_back(CodeTab + parent_class_name + " * __parent;\n");
    const auto self_array_dims = childArrayDims(mod);
    if (!self_array_dims.empty()) {
        for (size_t i = 0; i < self_array_dims.size(); ++i) {
            decl.push_back(CodeTab + "uint32_t __array_idx_" + std::to_string(i) + ";\n");
        }
    }
    decl.push_back("\n");

    // entry declarations
    decl.push_back("public:\n");
    decl.push_back("void " + TickFunctionName + "();\n");
    decl.push_back("void " + ApplyTickFunctionName + "();\n");
    decl.push_back("void __sys_reset();\n");
    decl.push_back("void __reg_reset();\n");
    decl.push_back("void reset() { __sys_reset(); __reg_reset(); }\n");
    decl.push_back("void init();\n");
    decl.push_back("\n");

    // constructor declaration
    string ctor_sig = mod_class_name + "(" + parent_class_name + " *parent";
    string ctor_init = "__parent(parent)";
    if (!self_array_dims.empty()) {
        for (size_t i = 0; i < self_array_dims.size(); ++i) {
            ctor_sig += ", uint32_t __idx" + std::to_string(i);
            ctor_init += ", __array_idx_" + std::to_string(i) + "(__idx" + std::to_string(i) + ")";
        }
    }
    ctor_sig += ")";
    decl.push_back(ctor_sig + " : " + ctor_init + " {\n");
    decl.push_back(CodeTab + "init();\n");
    decl.push_back(CodeTab + "__reg_reset();\n");
    decl.push_back("}\n");
    decl.push_back("\n");

    // private member declaration
    decl.push_back("private:\n");
    for (const auto &line : decl_private_field) {
        decl.push_back(line);
    }
    decl.push_back("\n");

    // public member declaration
    decl.push_back("public:\n");
    for (const auto &line : decl_public_field) {
        decl.push_back(line);
    }
    decl.push_back("\n");

    decl.push_back("};\n");
    decl.push_back("\n");



    vector<string> impl = genHeaderPrelude();

    impl.push_back("#include \"" + mod.simDeclPath() + "\"\n");
    impl.push_back("\n");

    // tick function implementations
    impl.push_back("void " + mod_class_name + "::" + TickFunctionName + "() {\n");
    for (const auto &id : mod.update_seq) {
        if (id == mod.instance_id) {
            // tick functions here
            for (uint64_t i = 0; i < mod.tick_blocks.size(); i++) {
                impl.push_back(CodeTab + "__tick" + std::to_string(i) + "();\n");
            }
        } else {
            for (const auto &inst_ptr : mod.children) {
                if (inst_ptr->instance_id == id) {
                    auto inst_decl_it = mod.instances.find(inst_ptr->instance_path.back());
                    if (inst_decl_it != mod.instances.end() && inst_decl_it->second.isArrayed()) {
                        forEachIndexTuple(inst_decl_it->second.array_dims, [&](const vector<ConfigRealValue> &indices) {
                            impl.push_back(CodeTab + childPtrFieldName(inst_ptr->instance_path.back(), indices) + "->" + TickFunctionName + "();\n");
                        });
                    } else {
                        impl.push_back(CodeTab + childPtrFieldName(inst_ptr->instance_path.back(), {}) + "->" + TickFunctionName + "();\n");
                    }
                    break;
                }
            }
        }
    }
    impl.push_back("}\n");
    impl.push_back("\n");

    // apply tick function implementations
    impl.push_back("void " + mod_class_name + "::" + ApplyTickFunctionName + "() {\n");
    impl.insert(impl.end(), impl_commit_field.begin(), impl_commit_field.end());
    impl.push_back("}\n");

    // sys reset function implementations
    impl.push_back("void " + mod_class_name + "::__sys_reset() {\n");
    impl.insert(impl.end(), impl_sys_reset_field.begin(), impl_sys_reset_field.end());
    impl.push_back("}\n");
    impl.push_back("\n");

    // reg reset function implementations
    impl.push_back("void " + mod_class_name + "::__reg_reset() {\n");
    impl.insert(impl.end(), impl_reg_reset_field.begin(), impl_reg_reset_field.end());
    impl.push_back("}\n");
    impl.push_back("\n");

    // init function implementations
    impl.push_back("void " + mod_class_name + "::init() {\n");
    impl.insert(impl.end(), impl_init_field.begin(), impl_init_field.end());
    impl.push_back("}\n");
    impl.push_back("\n");

    // other function implementations
    impl.insert(impl.end(), impl_field.begin(), impl_field.end());

    return {decl, impl, bram_resources_files};
}


vector<string> genStaticTestHarnessHpp(
    const VulStaticTestHarnessModule &test_module,
    const VulStaticModuleInstance &top_module,
    bool enable_tracing,
    const vector<VulBreakPointSpec> &break_specs,
    uint64_t break_cycles
) {
    
    vector<string> init_field;
    vector<string> member_field;
    vector<string> public_member_field;
    vector<string> simulation_field;
    vector<string> const_field;

    string child_instptr_name = "__instptr_top";
    string child_class_name = top_module.simClassName();

    member_field.push_back("std::unique_ptr<" + child_class_name + "> " + child_instptr_name + ";\n");
    init_field.push_back(CodeTab + child_instptr_name + " = std::make_unique<" + child_class_name + ">(this);\n");

    for (const auto &req_entry : test_module.requests) {
        const auto &req = req_entry.second;
        string rettype = req.returnType();
        string argnames = req.signatureArgNameList();
        string arglists = req.signatureArgOnly();
        const bool is_arrayed = !req.array_size.empty();
        if (is_arrayed) {
            member_field.push_back("template <uint32_t IDX = 0>\n");
        }
        member_field.push_back(rettype + " " + req_entry.first + "(" + arglists + ") {\n");
        string return_prefix = (rettype == "void" ? "" : "return ");
        if (is_arrayed) {
            member_field.push_back(CodeTab + return_prefix + child_instptr_name + "->" + req_entry.first + "<IDX>(" + argnames + ");\n");
        } else {
            member_field.push_back(CodeTab + return_prefix + child_instptr_name + "->" + req_entry.first + "(" + argnames + ");\n");
        }
        member_field.push_back("}\n");
        member_field.push_back("\n");
    }

    for (const auto &query_entry : test_module.queries) {
        const string &query_name = query_entry.first;
        const auto &decl_query = query_entry.second;
        auto top_query_it = top_module.queries.find(query_name);
        if (top_query_it == top_module.queries.end()) {
            throw VulException("TestMain QUERY '" + query_name + "' not found in top module '" + top_module.module_name + "'");
        }
        const auto &top_query = top_query_it->second;
        if (!(decl_query.ret_type == top_query.ret_type)) {
            throw VulException("TestMain QUERY '" + query_name + "' return type mismatch with top module query");
        }
        member_field.push_back(top_query.ret_type.toString() + " " + query_name + "() const {\n");
        member_field.push_back(CodeTab + "return " + child_instptr_name + "->" + query_name + "();\n");
        member_field.push_back("}\n");
        member_field.push_back("\n");
    }

    for (const auto &serve : test_module.services) {
        const auto &serv_name = serve.first;
        const auto &serv = serve.second;
        string rettype = serv.returnType();
        string argnames = serv.signatureArgNameList();
        string arglists = serv.signatureArgOnly();
        const bool is_arrayed = !serv.array_size.empty();

        if (is_arrayed) {
            public_member_field.push_back("template <uint32_t IDX = 0>\n");
        }
        public_member_field.push_back(rettype + " __wrapper_" + top_module.instance_path.back() + "_" + serve.first + "(" + arglists + ") {\n");
        if (serv.has_handshake) {
            if (is_arrayed) {
                public_member_field.push_back(CodeTab + "bool cond = __cond_" + serve.first + "<IDX>(" + argnames + ");\n");
                public_member_field.push_back(CodeTab + "if (cond) __impl_" + serve.first + "<IDX>(" + argnames + ");\n");
            } else {
                public_member_field.push_back(CodeTab + "bool cond = __cond_" + serve.first + "(" + argnames + ");\n");
                public_member_field.push_back(CodeTab + "if (cond) __impl_" + serve.first + "(" + argnames + ");\n");
            }
            public_member_field.push_back(CodeTab + "return cond;\n");
        } else {
            if (is_arrayed) {
                public_member_field.push_back(CodeTab + "__impl_" + serve.first + "<IDX>(" + argnames + ");\n");
            } else {
                public_member_field.push_back(CodeTab + "__impl_" + serve.first + "(" + argnames + ");\n");
            }
        }
        public_member_field.push_back("}\n");

        if (is_arrayed) {
            member_field.push_back("template <uint32_t IDX = 0>\n");
        }
        member_field.push_back("void __impl_" + serv_name + "(" + arglists + ") {\n");
        member_field.insert(member_field.end(), serv.codelines.begin(), serv.codelines.end());
        member_field.push_back("}\n");
        if (serv.has_handshake) {
            if (is_arrayed) {
                member_field.push_back("template <uint32_t IDX = 0>\n");
            }
            member_field.push_back("bool __cond_" + serv_name + "(" + arglists + ") {\n");
            member_field.push_back("return (" + serv.cond + ");\n");
            member_field.push_back("}\n");
        }
    }

    simulation_field = test_module.test_codelines;

    vector<string> out_lines = genHeaderPrelude();
    out_lines.push_back("#include \"common.h\"\n");
    out_lines.push_back("#include \"config.h\"\n");
    out_lines.push_back("#include \"bundle.h\"\n");
    out_lines.push_back("#include \"vullib.h\"\n");
    out_lines.push_back("\n");

    out_lines.push_back("#include \"" + top_module.simDeclPath() + "\"\n");
    out_lines.push_back("\n");

    for (const auto &includes : test_module.includedHeaders) {
        out_lines.push_back("#include <" + includes + ">\n");
    }
    out_lines.push_back("\n");

    string class_name = top_module.parent->simClassName();
    out_lines.push_back("class " + class_name + " {\n");

    out_lines.push_back("protected:\n");
    for (const auto &line : const_field) {
        out_lines.push_back(line);
    }
    for (const auto &line : test_module.globalCodes) {
        out_lines.push_back(line);
    }

    out_lines.push_back("public:\n");
    out_lines.push_back(class_name + "() {\n");
    for (const auto &line : init_field) {
        out_lines.push_back(line);
    }
    if (enable_tracing) {
        if (!break_specs.empty()) {
            out_lines.push_back(CodeTab + "trace_set_break_history_cycles(" + std::to_string(break_cycles) + ");\n");
            for (const auto &bp : break_specs) {
                std::string line = CodeTab + "trace_add_break_point({";
                for (size_t i = 0; i < bp.conditions.size(); ++i) {
                    if (i > 0) line += ", ";
                    const auto &cond = bp.conditions[i];
                    line += "{" + cppStringLiteral(cond.runtime_signal_name) + ", "
                                 + cppStringLiteral(cond.expected_bits) + ", "
                                 + cppStringLiteral(cond.expected_display) + "}";
                }
                line += "}, " + cppStringLiteral(bp.expr_text) + ");\n";
                out_lines.push_back(line);
            }
        }
        out_lines.push_back(CodeTab + "trace_init(\"trace.vcd\", 1, 1000);\n");
    }
    out_lines.push_back("}\n");
    out_lines.push_back("\n");
    out_lines.push_back("void simulation() {\n");
    for (const auto &line : simulation_field) {
        if (line.ends_with("\n")) {
            out_lines.push_back(line);
        } else {
            out_lines.push_back(line + "\n");
        }
    }
    out_lines.push_back("}\n");
    out_lines.push_back("\n");

    out_lines.insert(out_lines.end(), public_member_field.begin(), public_member_field.end());

    out_lines.push_back("protected:\n");
    out_lines.push_back("\n");

    out_lines.push_back("void sim_execute() {\n");
    out_lines.push_back(CodeTab + child_instptr_name + "->" + TickFunctionName + "();\n");
    out_lines.push_back("}\n");
    out_lines.push_back("\n");

    out_lines.push_back("void sim_commit() {\n");
    out_lines.push_back(CodeTab + child_instptr_name + "->" + ApplyTickFunctionName + "();\n");
    if (enable_tracing) {
        out_lines.push_back(CodeTab + "trace_commit();\n");
    }
    out_lines.push_back("}\n");
    out_lines.push_back("\n");

    out_lines.push_back("void sim_reset() {\n");
    out_lines.push_back(CodeTab + child_instptr_name + "->reset();\n");
    out_lines.push_back("}\n");
    out_lines.push_back("\n");

    for (const auto &line : member_field) {
        out_lines.push_back(line);
    }

    out_lines.push_back("};\n");
    out_lines.push_back("\n");

    return out_lines;
}

vector<string> genStaticTestMainHpp(shared_ptr<VulStaticModuleInstance> top_module) {
    
    vector<string> out_lines = genHeaderPrelude();

    out_lines.push_back("#include \"" + top_module->parent->simDeclPath() + "\"\n");
    out_lines.push_back("\n");

    // include all instances' impl headers
    std::deque<shared_ptr<VulStaticModuleInstance>> bfs_queue;
    bfs_queue.push_back(top_module);
    while (!bfs_queue.empty()) {
        auto mod_ptr = bfs_queue.front();
        bfs_queue.pop_front();
        out_lines.push_back("#include \"" + mod_ptr->simImplPath() + "\"\n");
        for (const auto &child : mod_ptr->children) {
            bfs_queue.push_back(child);
        }
    }

    out_lines.push_back("\n");

    // alias top-sim module's class name to VulTestMain
    string top_class_name = top_module->parent->simClassName();
    out_lines.push_back("using VulTestMain = " + top_class_name + ";\n");
    out_lines.push_back("\n");

    return out_lines;
}



} // namespace simgen
